# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/a06/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/a06

PRODUCT_COPY_FILES += \
    vendor/samsung/a06/proprietary/bin/lpm:$(TARGET_COPY_OUT_SYSTEM)/bin/lpm \
    vendor/samsung/a06/proprietary/etc/init/init.sec-charger.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/init.sec-charger.rc \
    vendor/samsung/a06/proprietary/etc/init/init.dt2w.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/init.dt2w.rc \
    vendor/samsung/a06/proprietary/lib64/libmaet.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmaet.so \
    vendor/samsung/a06/proprietary/lib64/libshowlogo.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libshowlogo.so \
    vendor/samsung/a06/proprietary/lib64/libsxqk_skia.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsxqk_skia.so \
    vendor/samsung/a06/proprietary/media/battery_error.spi:$(TARGET_COPY_OUT_SYSTEM)/media/battery_error.spi \
    vendor/samsung/a06/proprietary/media/battery_lightning.spi:$(TARGET_COPY_OUT_SYSTEM)/media/battery_lightning.spi \
    vendor/samsung/a06/proprietary/media/battery_lightning_fast.spi:$(TARGET_COPY_OUT_SYSTEM)/media/battery_lightning_fast.spi \
    vendor/samsung/a06/proprietary/media/battery_low.spi:$(TARGET_COPY_OUT_SYSTEM)/media/battery_low.spi \
    vendor/samsung/a06/proprietary/media/battery_temperature_error.spi:$(TARGET_COPY_OUT_SYSTEM)/media/battery_temperature_error.spi \
    vendor/samsung/a06/proprietary/media/battery_temperature_limit.spi:$(TARGET_COPY_OUT_SYSTEM)/media/battery_temperature_limit.spi \
    vendor/samsung/a06/proprietary/media/battery_water_usb.spi:$(TARGET_COPY_OUT_SYSTEM)/media/battery_water_usb.spi \
    vendor/samsung/a06/proprietary/media/charging_vi_100.spi:$(TARGET_COPY_OUT_SYSTEM)/media/charging_vi_100.spi \
    vendor/samsung/a06/proprietary/media/charging_vi_level1.spi:$(TARGET_COPY_OUT_SYSTEM)/media/charging_vi_level1.spi \
    vendor/samsung/a06/proprietary/media/charging_vi_level2.spi:$(TARGET_COPY_OUT_SYSTEM)/media/charging_vi_level2.spi \
    vendor/samsung/a06/proprietary/media/charging_vi_level3.spi:$(TARGET_COPY_OUT_SYSTEM)/media/charging_vi_level3.spi \
    vendor/samsung/a06/proprietary/media/charging_vi_level4.spi:$(TARGET_COPY_OUT_SYSTEM)/media/charging_vi_level4.spi \
    vendor/samsung/a06/proprietary/media/dock_error_usb.spi:$(TARGET_COPY_OUT_SYSTEM)/media/dock_error_usb.spi \
    vendor/samsung/a06/proprietary/media/incomplete_connect.spi:$(TARGET_COPY_OUT_SYSTEM)/media/incomplete_connect.spi \
    vendor/samsung/a06/proprietary/media/lcd_density.txt:$(TARGET_COPY_OUT_SYSTEM)/media/lcd_density.txt \
    vendor/samsung/a06/proprietary/media/percentage.spi:$(TARGET_COPY_OUT_SYSTEM)/media/percentage.spi \
    vendor/samsung/a06/proprietary/media/safety_timer_usb.spi:$(TARGET_COPY_OUT_SYSTEM)/media/safety_timer_usb.spi \
    vendor/samsung/a06/proprietary/media/slow_charging_usb.spi:$(TARGET_COPY_OUT_SYSTEM)/media/slow_charging_usb.spi \
    vendor/samsung/a06/proprietary/media/temperature_limit_usb.spi:$(TARGET_COPY_OUT_SYSTEM)/media/temperature_limit_usb.spi \
    vendor/samsung/a06/proprietary/media/water_protection_usb.spi:$(TARGET_COPY_OUT_SYSTEM)/media/water_protection_usb.spi \
    vendor/samsung/a06/proprietary/system_ext/lib/vendor.mediatek.hardware.mtkradioex@3.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vendor.mediatek.hardware.mtkradioex@3.0.so \
    vendor/samsung/a06/proprietary/system_ext/lib64/vendor.mediatek.hardware.mtkradioex@3.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.mediatek.hardware.mtkradioex@3.0.so

PRODUCT_PACKAGES += \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-base 
